//
//  ListCharactersModels.swift
//  BobsBDemo
//
//  Created by Gokul Krishna on 08/06/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListCharacters
{
  // MARK: Use cases
  
  enum FetchCharacters
  {
    struct Request {
    }
    struct Response {
        var characters: [Character]
    }
    struct ViewModel {
        struct DisplayedCharacter {
          var id: String
          var name: String
          var image: String
          var voicedBy: String
        }
        var displayedCharacter: [DisplayedCharacter]
    }
  }
    enum FetchCharactersImage
    {
      struct Request {
          var url: String
      }
      struct Response {
          var image: UIImage
      }
      struct ViewModel {
          struct DisplayedCharacterImage {
              var image: UIImage
          }
          var displayedCharacter: DisplayedCharacterImage
      }
    }
}
