//
//  ListCharactersWorker.swift
//  BobsBDemo
//
//  Created by Gokul Krishna on 08/06/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListCharactersWorker {
    var charactersStore: CharactersStoreProtocol
    
    init(charactersStore: CharactersStoreProtocol)
    {
      self.charactersStore = charactersStore
    }
    func fetchCharacters(completionHandler: @escaping ([Character]) -> Void) {
        charactersStore.fetchCharacters { (characters: [Character]) -> Void in
            DispatchQueue.main.async {
              completionHandler(characters)
          }
        }
      }
}

protocol CharactersStoreProtocol
{
  // MARK: CRUD operations - Optional error
  
    func fetchCharacters(completionHandler: @escaping ([Character]) -> Void)
}

protocol CharactersStoreUtilityProtocol {}

enum CharactersStoreError: Equatable, Error
{
  case CannotFetch(String)
}
