//
//  ListCharactersInteractorTests.swift
//  BobsBDemo
//
//  Created by Gokul Krishna on 08/06/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import BobsBDemo
import XCTest

class ListCharactersInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListCharactersInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListCharactersInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListCharactersInteractor()
  {
    sut = ListCharactersInteractor()
  }
  
  // MARK: Test doubles
  
  class ListCharactersPresentationLogicSpy: ListCharactersPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: ListCharacters.FetchCharacters.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = ListCharactersPresentationLogicSpy()
    sut.presenter = spy
    let request = ListCharacters.FetchCharacters.Request()
    
    // When
    sut.fetchCharacters(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
