//
//  ListCharactersPresenterTests.swift
//  BobsBDemo
//
//  Created by Gokul Krishna on 08/06/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import BobsBDemo
import XCTest

class ListCharactersPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListCharactersPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListCharactersPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListCharactersPresenter()
  {
    sut = ListCharactersPresenter()
  }
  
  // MARK: Test doubles
  
  class ListCharactersDisplayLogicSpy: ListCharactersDisplayLogic
    {
      
    var displayFetchCharactersCalled = false
    
      var viewModel: ListCharacters.FetchCharacters.ViewModel!
      
    func displayFetchCharacters(viewModel: ListCharacters.FetchCharacters.ViewModel)
    {
        displayFetchCharactersCalled = true
        self.viewModel = viewModel
    }
  }
  
  // MARK: Tests
  
  func testPresentFetchedCharactersShouldFormatFetchedCharactersForDisplay()
  {
    // Given
    let spy = ListCharactersDisplayLogicSpy()
    sut.viewController = spy
      
    // When
      let testCharacter1 = Seeds.Charecters.testCharacter1
      
      let characters = [testCharacter1]
      
      let response = ListCharacters.FetchCharacters.Response(characters: characters)
      sut.presentFetchCharacters(response: response)
    
    // Then
      let displayedCharacters = spy.viewModel.displayedCharacter
      for displayedCharacter in displayedCharacters {
        XCTAssertEqual(displayedCharacter.id, 1, "Presenting fetched orders should properly format order ID")
          XCTAssertEqual(displayedCharacter.name, "", "Presenting fetched orders should properly format order date")
      }
  }
}
